command.suppressor.add.description=Fügt eine neue Region hinzu
command.suppressor.add.usage=/suppressor add <x> <y> <z> <x> <y> <z>
command.suppressor.edit.description=Editiert die aktuelle Region
command.suppressor.edit.usage=/suppressor edit <x> <y> <z> <x> <y> <z>
command.suppressor.error.wrong_usage=Bitte nutze {0}.
command.suppressor.help.description=Zeigt das Hilfemenü an
command.suppressor.help.menu=Liste aller verfügbaren Unterbefehle:
command.suppressor.help.usage=/suppressor help
command.suppressor.reload.description=Läd die Konfigurationen neu
command.suppressor.reload.failure=Fehler beim neuladen der Konfigurationen.
command.suppressor.reload.success=Konfigurationen neu geladen.
command.suppressor.reload.usage=/suppressor reload
command.suppressor.remove.description=Entfernt die aktuelle Region
command.suppressor.remove.usage=/suppressor remove
command.suppressor.toggle.description=Zeigt die Regionen an
command.suppressor.toggle.usage=/suppressor toggle
