command.suppressor.error.wrong_usage=Bitte nutze {0}.
command.suppressor.help.description=Zeigt das Hilfemenü an
command.suppressor.help.menu=Liste aller verfügbaren Unterbefehle:
command.suppressor.help.usage=/suppressor help
command.suppressor.reload.description=Läd die Konfigurationen neu
command.suppressor.reload.failure=Fehler beim neuladen der Konfigurationen.
command.suppressor.reload.success=Konfigurationen neu geladen.
command.suppressor.reload.usage=/suppressor reload